name: Run Supabase Listener

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install --upgrade pip setuptools wheel
          pip install aiohttp
          pip install supabase_client
          pip install -r requirements.txt

      - name: Run main.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_TABLE: ${{ secrets.SUPABASE_TABLE }}
        run:
          python newEntryListener.py
